<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.formsdirectinc.qa.EndToEndTest"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="57.161">
  <properties />
      <testcase name="endTest" time="0.000">
            <failure type="org.openqa.selenium.remote.SessionNotFoundException"
                  message="The FirefoxDriver cannot be used after quit() was called.
Build info: version: &apos;2.47.2&apos;, revision: &apos;4d972c01cab1304452627f837654326a11eb92fe&apos;, time: &apos;2015-09-24 09:17:17&apos;
System info: host: &apos;otywin-17&apos;, ip: &apos;10.0.102.178&apos;, os.name: &apos;Windows 7&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.1&apos;, java.version: &apos;1.8.0_25&apos;
Driver info: driver.version: FirefoxDriver"
              >
<![CDATA[org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.47.2', revision: '4d972c01cab1304452627f837654326a11eb92fe', time: '2015-09-24 09:17:17'
System info: host: 'otywin-17', ip: '10.0.102.178', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
  org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:390)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:568)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:618)
  org.openqa.selenium.firefox.FirefoxDriver.getScreenshotAs(FirefoxDriver.java:354)
  com.formsdirectinc.qa.utils.CaptureScreen.takeScreenShot(CaptureScreen.java:61)
  com.formsdirectinc.qa.TestBase.endTest(TestBase.java:66)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
  org.testng.TestRunner.afterRun(TestRunner.java:1012)
  org.testng.TestRunner.run(TestRunner.java:636)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
      <testcase name="start" time="57.161" />
  
</testsuite>
